_posts/2014-07-24-midnight.markdown
=> Lowercase 'Midnight' URLS

_posts/2014-02-05-hikari.markdown
Hi,
I changed my username and therefore need to correct those URLs so that they point to the correct repo.
Cheers!
=> hikari: amended URL path

_config.yml, index.html
=> Add pagination to index

_posts/2016-04-05-iceandfire.markdown
http:// and not https:// for Demo! :)
http://lucasgatsas.ch
=> Update - 2016-04-05-iceandfire.markdown - http://

_posts/2013-08-23-lagom.markdown
=> Add Lagom demo url

_posts/2015-07-05-personal.markdown
Fixed broken urls and updated description.
=> Updated { Personal }

_posts/2015-08-20-read-only.markdown
Demo link from html5up the makers of the theme
=> Added demo link

_posts/2015-08-20-strata.markdown
=> Added demo link for strata

_posts/2015-08-20-twenty.markdown
=> Add demo link for twenty theme

_posts/2015-08-20-dopetrope.markdown
=> Add demo link for dopetrope theme

_posts/2016-02-01-evento.markdown
=> Updated broken image link

_posts/2014-05-04-CleanMagicMedium.markdown
New Update !
#Library Jekyll - V.0.0.1
=> Update - Library Jekyll on Math

_layouts/default.html
Thought it would be nice to link to the repo for those who miss the fork button.
=> Link to jekyllthemes repo.

_posts/2016-09-13-space-jekyll-template.markdown
=> homepage and demo link updated

_posts/2015-12-24-two-column.markdown
changed sites and updated post information to match
=> updated demo to right site

_posts/2015-09-11-daktilo.markdown
Concerning this [issue](https://github.com/kronik3r/daktilo/issues/22) on Daktillo theme for [Jekyllthemes.org](Jekyllthemes.org)
=> Update demo url for Daktillo theme

_posts/2016-02-24-mangan.markdown
Hi @mattvh and @gynter. I see so many PR on there, could you review all of those? :)
=> Update author name on Mangan theme

_posts/2016-02-12-accent.markdown, _posts/2016-08-30-researcher.markdown
I have recently changed my domain name from http://ankitsultana.me to http://ankitsultana.com . I have updated the urls of my jekyll themes to reflect the same.
=> update domain names for my jekyll themes

_posts/2017-03-23-webjeda-ashwath.markdown
there is an invalid date: switched month and day I guess. Jekyll would not compile the site because of this.
=> fixed invalid date

_posts/2016-06-27-Jalpc-A.markdown
=> Jalpc-A demo site no longer active

_posts/2017-06-01-marat.markdown
=> corrected demo link

_posts/2016-01-10-Chaplin.markdown, _posts/2016-02-12-accent.markdown, _posts/2016-08-30-researcher.markdown
I recently changed my username. This commit updates references to my themes.
=> update my username on all my themes

_posts/2019-02-20-hydrogen.md
This is a very simple PR to rename the hydrogen theme file so it agrees with the right format.
=> Rename hydrogen.md file

_posts/2017-12-07-jekyll-theme-prologue.md
Fix broken image src, update feature list
=> prologue-edits

_posts/2018-05-30-HardCandy-Jekyll.md
=> Update hard candy jekyll

_posts/2020-03-03-creative-theme-jekyll-new.markdown
No screenshot provided as it would be the same as creative-theme-jekyll.
=> Added creative-theme-jekyll-new theme.

_posts/2019-05-5-PlainWhite-Jekyll.md, _posts/2019-06-30-Texture-Theme.md
For these:
http://jekyllthemes.org/themes/PlainWhite-Jekyll/
http://jekyllthemes.org/themes/Texture-Theme/
=> Plainwhite & Texture: Update theme links

_posts/2015-01-02-uno-dbyll.markdown, _posts/2018-06-20-flexton.md
I noticed these two posts weren't displaying correctly on the site. These were simple edits to the front matter.
=> Fixed 2 display issues.
